'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tracks=[['DEEP SPACE SIGNAL',110,88.3],['AFTER THE ORBIT',146.83,94.7],['DISTANT HORIZONS',130.81,101.9]];
let ctx,ambient=[],gain,playing=false,playPending=false,track=0,position=0,localURL=null,localName='',source='radio',toastTimer,scanTimer,scanToken=0,scanning=false,scanTarget=0,playToken=0,scanResume=false;
let prefs={motion:true,glow:true,sounds:false,intensity:100,volume:25};
try{const saved=JSON.parse(localStorage.getItem('frontier-prefs')||'{}');for(const k of ['motion','glow','sounds'])if(typeof saved[k]==='boolean')prefs[k]=saved[k];for(const k of ['intensity','volume'])if(Number.isFinite(saved[k]))prefs[k]=Math.min(100,Math.max(k==='intensity'?50:0,saved[k]));}catch{}
for(const key of ['motion','glow','sounds'])$('#'+key).checked=prefs[key];$('#intensity').value=prefs.intensity;$('#volume').value=prefs.volume;
function applyPrefs(){document.body.classList.toggle('no-glow',!prefs.glow);document.documentElement.style.setProperty('--intensity',prefs.intensity/100);try{localStorage.setItem('frontier-prefs',JSON.stringify(prefs))}catch{}}
applyPrefs();
function audioContext(){if(!ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('Audio unavailable');ctx=new Audio();}return ctx;}
function clickSound(){} // Centralized feedback lives in enhancements.js.
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400);}
function showView(view){if(view==='media')view='radio';if(!['cockpit','navigation','data','radio','spotify','systems'].includes(view))view='cockpit';$$('.view').forEach(e=>e.classList.toggle('active',e.id===view));$$('nav button').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});history.replaceState(null,'','#'+view);$('#main').scrollTop=0;if(view==='data')renderData();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{clickSound();showView(b.dataset.view);}));window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));
function updatePlay(){
  $$('.play').forEach(b=>{const external=source==='spotify'&&!b.closest('#radio');b.textContent=external?'↗':scanning?'■':playing?'Ⅱ':'▶';b.setAttribute('aria-label',external?'Open Spotify player':scanning?'Cancel station scan':playing?'Pause audio':'Play audio');b.setAttribute('aria-pressed',String(!external&&playing));b.disabled=playPending;});
  document.body.classList.toggle('radio-playing',playing&&!scanning&&source==='radio');
}
function updateNames(){
  const name=localURL?localName:tracks[track][0];$$('.track-name').forEach(e=>e.textContent=source==='spotify'&&!e.closest('#radio')?'SPOTIFY / PLAYER LOADED':name);
  $('#artist').textContent=localURL?'AUXILIARY / LOCAL FILE':'DEEP SPACE RADIO / AMBIENT DEMO';
  $$('.playlist button').forEach((b,i)=>{b.classList.toggle('active',!localURL&&i===track);b.setAttribute('aria-pressed',String(!localURL&&i===track));});
}
function stopAmbient(){ambient.forEach(o=>{try{o.stop();o.disconnect();}catch{}});ambient=[];if(gain){gain.disconnect();gain=null;}}
function stopPlayback(){playToken++;playPending=false;$('#audio').pause();stopAmbient();playing=false;updatePlay();}
function startAmbient(){stopAmbient();const c=audioContext();gain=c.createGain();gain.gain.value=prefs.volume/100*.07;gain.connect(c.destination);[1,1.5,2.003].forEach(m=>{const o=c.createOscillator();o.type='sine';o.frequency.value=tracks[track][1]*m;o.connect(gain);o.start();ambient.push(o);});}
function scanNoise(){try{const c=audioContext(),buffer=c.createBuffer(1,c.sampleRate*.25,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.2;const node=c.createBufferSource();node.buffer=buffer;node.loop=true;gain=c.createGain();gain.gain.value=prefs.volume/100*.07;node.connect(gain).connect(c.destination);node.start();ambient.push(node);}catch{}}
function releaseLocal(){if(localURL)URL.revokeObjectURL(localURL);localURL=null;localName='';$('#audio').removeAttribute('src');$('#audio-file').value='';$('#seek').max=180;$('#duration').textContent='3:00';}
function displayFrequency(value){$('#frequency').textContent=value.toFixed(1);$('#tuning-needle').style.left=Math.max(0,Math.min(100,(value-88)/20*100))+'%';}
function cancelScan(){clearInterval(scanTimer);scanToken++;scanning=false;$('#radio').classList.remove('scanning');stopAmbient();displayFrequency(tracks[track][2]);$('#tuner-state').textContent=localURL?'AUXILIARY INPUT':'SIGNAL LOCKED';$('#station-id').textContent=localURL?'LOCAL FILE':'CH 0'+(track+1)+' / '+tracks[track][0];updatePlay();}
function disconnectSpotify(announce=false){const frame=$('#spotify-player iframe');if(frame)frame.remove();$('#spotify-player').innerHTML=spotifyPlaceholder;$('#spotify-status').textContent='No Spotify player loaded.';$('#disconnect-spotify').disabled=true;source='radio';updateNames();updatePlay();if(announce)toast('Spotify player unloaded');}
async function togglePlay(){
  if(scanning){cancelScan();playing=false;updatePlay();return;}
  if(playing||playPending){stopPlayback();return;}
  if(source==='spotify')disconnectSpotify();
  const token=++playToken;playPending=true;updatePlay();
  try{if(localURL){if($('#audio').ended)$('#audio').currentTime=0;await $('#audio').play();}else{await audioContext().resume();if(token!==playToken)return;startAmbient();}if(token!==playToken)return;playing=true;}
  catch{if(token===playToken){playing=false;toast('Audio could not play. Try another file or tap Play again.');}}
  finally{if(token===playToken){playPending=false;updatePlay();}}
}
function chooseTrack(index){
  const resume=playing||(scanning&&scanResume);scanResume=resume;cancelScan();stopPlayback();if(source==='spotify')disconnectSpotify();releaseLocal();position=0;scanTarget=(index+tracks.length)%tracks.length;
  scanning=true;const token=++scanToken,target=scanTarget,start=tracks[track][2],finish=tracks[target][2];$('#radio').classList.add('scanning');$('#tuner-state').textContent='SCANNING BAND';$('#station-id').textContent='SEEK / SEARCHING CHANNELS';updatePlay();if(resume&&!document.hidden)scanNoise();
  let step=0;const total=10;scanTimer=setInterval(()=>{if(token!==scanToken)return;step++;displayFrequency(start+(finish-start)*step/total);$('#station-id').textContent='SEEK / '+(start+(finish-start)*step/total).toFixed(1)+' MHz';if(step>=total){clearInterval(scanTimer);track=target;scanning=false;$('#radio').classList.remove('scanning');stopAmbient();displayFrequency(finish);$('#tuner-state').textContent='SIGNAL LOCKED';$('#station-id').textContent='CH 0'+(track+1)+' / '+tracks[track][0];updateNames();updateProgress();updatePlay();if(resume&&!document.hidden)togglePlay();}},120);
}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{clickSound();if(source==='spotify'&&!b.closest('#radio')){showView('spotify');return;}if(b.dataset.action==='play')togglePlay();else chooseTrack((scanning?scanTarget:track)+(b.dataset.action==='next'?1:-1));}));
$('#playlist').innerHTML=tracks.map((t,i)=>`<button data-track="${i}">0${i+1} / ${t[2]} MHz<br>${t[0]}</button>`).join('');$$('[data-track]').forEach(b=>b.onclick=()=>chooseTrack(Number(b.dataset.track)));
$('#waveform').innerHTML=Array.from({length:55},(_,i)=>`<i style="height:${15+Math.abs(Math.sin(i*1.7)*Math.cos(i*.31))*85}%"></i>`).join('');
function formatTime(n){if(!Number.isFinite(n))return '0:00';return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;}
function updateProgress(){const p=localURL?$('#audio').currentTime:position;$('#seek').value=p;$('#elapsed').textContent=formatTime(p);}
$('#seek').oninput=e=>{if(localURL&&Number.isFinite($('#audio').duration))$('#audio').currentTime=Number(e.target.value);else position=Number(e.target.value);updateProgress();};
$('#volume').oninput=e=>{prefs.volume=Number(e.target.value);$('#audio').volume=prefs.volume/100;if(gain)gain.gain.value=prefs.volume/100*.07;applyPrefs();};$('#audio').volume=prefs.volume/100;
$('#audio-file').onchange=e=>{const f=e.target.files[0];if(!f)return;cancelScan();stopPlayback();if(source==='spotify')disconnectSpotify();releaseLocal();localURL=URL.createObjectURL(f);localName=f.name.replace(/\.[^.]+$/,'');$('#audio').src=localURL;position=0;$('#seek').max=0;$('#duration').textContent='0:00';$('#tuner-state').textContent='AUXILIARY INPUT';$('#station-id').textContent='LOCAL FILE / NO BROADCAST';updateNames();updatePlay();updateProgress();toast('Audio loaded. Press play.');};
$('#audio').addEventListener('loadedmetadata',()=>{if(localURL&&Number.isFinite($('#audio').duration)){$('#seek').max=$('#audio').duration;$('#duration').textContent=formatTime($('#audio').duration);}});
$('#audio').addEventListener('timeupdate',updateProgress);
$('#audio').addEventListener('ended',()=>{playing=false;updatePlay();});
$('#audio').addEventListener('pause',()=>{if(localURL){playing=false;updatePlay();}});
$('#audio').addEventListener('error',()=>{if(localURL){stopPlayback();toast('This audio format could not be opened.');}});
for(const key of ['motion','glow','sounds','intensity'])$('#'+key).addEventListener('input',e=>{prefs[key]=key==='intensity'?Number(e.target.value):e.target.checked;applyPrefs();});
const spotifyPlaceholder=$('#spotify-player').innerHTML;
try{$('#spotify-url').value=localStorage.getItem('frontier-spotify-url')||'';}catch{}
$('#spotify-form').onsubmit=e=>{e.preventDefault();let u;try{u=new URL($('#spotify-url').value.trim());}catch{u=null;}
  const match=u&&u.protocol==='https:'&&u.hostname==='open.spotify.com'&&!u.username&&!u.password&&u.pathname.match(/^\/(?:intl-[a-z-]+\/)?(track|album|playlist|artist|episode|show)\/([A-Za-z0-9]{22})\/?$/);
  if(!match){$('#spotify-status').textContent='Use an open.spotify.com track, album, or playlist share link.';return;}
  cancelScan();stopPlayback();source='spotify';const frame=document.createElement('iframe');frame.title='Spotify music player';frame.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';frame.src='https://open.spotify.com/embed/'+match[1]+'/'+match[2]+'?theme=0';$('#spotify-player').replaceChildren(frame);$('#disconnect-spotify').disabled=false;$('#spotify-status').textContent='Spotify player requested. Use its playback controls; availability depends on Spotify.';try{localStorage.setItem('frontier-spotify-url',u.origin+u.pathname);}catch{}updateNames();updatePlay();};
$('#disconnect-spotify').onclick=()=>disconnectSpotify(true);
let routeRunning=false,routeProgress=0,zoom=1;const distances=[4.2,7.8,2.6],destinations=['DOWNTOWN','ORBITAL STATION','HOME BASE'];
function resetRoute(){routeProgress=0;routeRunning=false;$('#route-toggle').textContent='START ROUTE';$('#route-state').textContent='ROUTE READY';renderRoute()}
function renderRoute(){const selected=Number($('#destination').value),d=distances[selected];$('#remaining').textContent=(d*(1-routeProgress)).toFixed(1);$('#eta').textContent=Math.ceil(d*2.85*(1-routeProgress));$('#home-dest').textContent=destinations[selected];$('#home-distance').textContent=(d*(1-routeProgress)).toFixed(1);$('#home-eta').textContent='EST. '+Math.ceil(d*2.85*(1-routeProgress))+' MIN';$('#home-route-state').textContent=routeProgress>=1?'DESTINATION REACHED':routeRunning?'ROUTE SIMULATOR / ACTIVE':routeProgress>0?'ROUTE SIMULATOR / PAUSED':'ROUTE SIMULATOR / STANDBY';const line=$('#route-line'),p=line.getPointAtLength(line.getTotalLength()*routeProgress);$('#position').setAttribute('transform',`translate(${p.x} ${p.y})`);$('#turn-distance').textContent=routeProgress>=1?'ARRIVED':(Math.max(.1,.4*(1-(routeProgress*3)%1))).toFixed(1)+' MI';$('#turn-street').textContent=routeProgress>=1?'DESTINATION REACHED':routeProgress<.3?'EAST ON KENNEDY ST':routeProgress<.7?'NORTH TOWARD MAIN ST':'EAST ON MAIN ST';$('#turn-arrow').textContent=routeProgress>=1?'◈':routeProgress<.3?'↱':routeProgress<.7?'↰':'↱'}
$('#destination').onchange=resetRoute;
$('#route-toggle').onclick=()=>{clickSound();if(routeProgress>=1)routeProgress=0;routeRunning=!routeRunning;$('#route-toggle').textContent=routeRunning?'PAUSE ROUTE':'RESUME ROUTE';$('#route-state').textContent=routeRunning?'ROUTE ENGAGED / SIMULATION':'ROUTE PAUSED';if(routeRunning)toast('Route simulation engaged');renderRoute()};
function renderZoom(){$('.map-scale span').textContent=(.5/zoom).toFixed(2)+' MI / DEMO';$('#map-world').setAttribute('transform',`translate(${300-300*zoom} ${250-250*zoom}) scale(${zoom})`)}$('#zoom-in').onclick=()=>{zoom=Math.min(2.5,zoom+.25);renderZoom()};$('#zoom-out').onclick=()=>{zoom=Math.max(.75,zoom-.25);renderZoom()};$('#recenter').onclick=()=>{zoom=1;renderZoom()};
const telemetry=new TelemetrySession();let frozenSnapshot=null;
const metrics=[{key:'speed',label:'GROUND SPEED',unit:'MPH',min:0,max:80,digits:0},{key:'rpm',label:'ENGINE SPEED',unit:'RPM',min:0,max:4000,digits:0},{key:'coolant',label:'COOLANT TEMP',unit:'°F',min:160,max:220,digits:1},{key:'voltage',label:'SYSTEM VOLTAGE',unit:'V',min:12,max:15,digits:2}];
$('#chart-grid').innerHTML=metrics.map(m=>`<article class="panel chart-panel"><div class="chart-top"><h2>${m.label}</h2><div class="chart-reading"><span id="value-${m.key}">—</span><small>${m.unit}</small></div></div><svg class="chart" id="chart-${m.key}" viewBox="0 0 360 150" role="img" aria-label="${m.label} graph in ${m.unit}, simulated data"><g>${[0,.5,1].map(f=>`<path class="grid-line" d="M35 ${12+112*f}H350"/><text x="0" y="${15+112*f}">${m.max-(m.max-m.min)*f}</text>`).join('')}</g><path class="area"/><path class="trace"/><circle class="point" r="2.5" cx="350" cy="124"/><text x="35" y="147" class="start-label">−60s</text><text x="327" y="147">NOW</text></svg><div class="chart-stats"><span>MIN<b id="min-${m.key}">—</b></span><span>AVG<b id="avg-${m.key}">—</b></span><span>MAX<b id="max-${m.key}">—</b></span></div></article>`).join('');
function renderData(){const snap=frozenSnapshot||telemetry.snapshot(),win=Number($('#history-window').value),rows=snap.history.filter(r=>r.t>snap.elapsed-win);$('#session-time').textContent=formatTime(snap.elapsed);$('#session-distance').textContent=snap.distance.toFixed(2);$('#session-average').textContent=snap.average.toFixed(1);$('#session-peak').textContent=snap.peak.toLocaleString();$('#sample-count').textContent=snap.count+' SAMPLES';$('#history-status').textContent='LAST '+win+' SECONDS';
  for(const m of metrics){const vals=rows.map(r=>r[m.key]),last=vals.at(-1);$('#value-'+m.key).textContent=last===undefined?'—':last.toFixed(m.digits);for(const k of ['min','avg','max'])$('#'+k+'-'+m.key).textContent=vals.length?(k==='min'?Math.min(...vals):k==='max'?Math.max(...vals):vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(m.digits):'—';
    const points=rows.map(r=>[35+315*(1-(snap.elapsed-r.t)/win),124-112*Math.max(0,Math.min(1,(r[m.key]-m.min)/(m.max-m.min)))]),chart=$('#chart-'+m.key),path=points.map((p,i)=>(i?'L':'M')+p.map(v=>v.toFixed(2)).join(' ')).join(' ');chart.querySelector('.trace').setAttribute('d',path);chart.querySelector('.area').setAttribute('d',points.length?path+' L'+points.at(-1)[0]+' 124 L'+points[0][0]+' 124 Z':'');const dot=chart.querySelector('.point');dot.style.display=points.length?'':'none';if(points.length){dot.setAttribute('cx',points.at(-1)[0]);dot.setAttribute('cy',points.at(-1)[1]);}chart.querySelector('.start-label').textContent='−'+win+'s';chart.setAttribute('aria-label',m.label+': '+(last===undefined?'no samples':last.toFixed(m.digits)+' '+m.unit)+', '+rows.length+' simulated samples in the last '+win+' seconds');}
}
function updateTelemetry(row){$('#speed').textContent=row.speed;$('#rpm').textContent=row.rpm.toLocaleString();$$('.live-speed').forEach(e=>e.textContent=row.speed);$$('.live-rpm').forEach(e=>e.textContent=row.rpm.toLocaleString());$$('.live-coolant').forEach(e=>e.textContent=row.coolant.toFixed(0));$$('.live-voltage').forEach(e=>e.textContent=row.voltage.toFixed(1));$$('.live-fuel').forEach(e=>e.textContent=row.fuel.toFixed(0));$$('.live-load').forEach(e=>e.textContent=row.load.toFixed(0));$$('.live-throttle').forEach(e=>e.textContent=row.throttle.toFixed(0));$$('.live-intake').forEach(e=>e.textContent=row.intake.toFixed(0));const snap=telemetry.snapshot();$('#home-average').textContent=snap.average.toFixed(1);$('#home-trip').textContent=snap.distance.toFixed(2);$('#home-peak').textContent=snap.peak.toLocaleString();if($('#data').classList.contains('active'))renderData();}
$('#history-window').onchange=renderData;
$('#freeze-data').onclick=()=>{frozenSnapshot=frozenSnapshot?null:telemetry.snapshot();$('#freeze-data').textContent=frozenSnapshot?'RESUME GRAPHS':'FREEZE GRAPHS';$('#capture-status').textContent=frozenSnapshot?'Ⅱ FROZEN VIEW':'● RECORDING';$('#capture-status').classList.toggle('frozen',!!frozenSnapshot);renderData();};
$('#reset-data').onclick=()=>{telemetry.reset();frozenSnapshot=null;$('#freeze-data').textContent='FREEZE GRAPHS';$('#capture-status').textContent='● RECORDING';$('#capture-status').classList.remove('frozen');$('#home-average').textContent='0.0';$('#home-trip').textContent='0.00';$('#home-peak').textContent='0';renderData();toast('Telemetry session reset');};
function tick(){if(document.hidden)return;$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});updateTelemetry(telemetry.sample(prefs.motion));if(playing&&!localURL&&!scanning){position++;if(position>=180)position=0;updateProgress();}if(routeRunning){routeProgress=Math.min(1,routeProgress+1/90);if(routeProgress>=1){routeRunning=false;$('#route-toggle').textContent='REPLAY ROUTE';$('#route-state').textContent='DESTINATION REACHED';toast('Destination reached');}renderRoute();}}
updateNames();updatePlay();displayFrequency(tracks[track][2]);renderRoute();renderData();showView(location.hash.slice(1));tick();setInterval(tick,1000);
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(scanning){cancelScan();playing=false;}if(playing&&!localURL)stopPlayback();updatePlay();}else if(ctx&&ctx.state==='suspended'&&playing&&!localURL){stopPlayback();}});
