'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const truck=`<svg viewBox="0 0 300 190" role="img" aria-label="Holographic pickup truck schematic"><g fill="none" stroke="#ff9b43" stroke-width="1.2" stroke-linejoin="round"><ellipse cx="150" cy="145" rx="120" ry="30" stroke="#74431e"/><ellipse cx="150" cy="145" rx="95" ry="23" stroke="#74431e"/><path d="M31 114L64 93L95 88L124 46L186 60L207 99L264 116L264 138L230 158L31 130Z M31 114L91 130L129 104L95 88 M91 130V148L230 158 M129 104L207 99L264 116L230 137L91 130 M230 137V158 M105 86L129 55L153 61L149 98Z M159 64L181 70L196 96L158 99Z M153 61L159 64 M149 98L158 99 M156 102V140 M98 106L94 129 M178 108L215 113L243 122L226 132L184 124Z M41 115L77 126 M42 122L77 132 M165 109L178 111"/><path d="M67 132C55 122 46 129 47 141C48 158 69 164 74 149L74 135 M213 149C202 139 193 147 195 158C198 176 219 177 222 161L221 152" fill="#0c1010"/><ellipse cx="61" cy="144" rx="8" ry="12" transform="rotate(-23 61 144)"/><ellipse cx="208" cy="161" rx="8" ry="12" transform="rotate(-23 208 161)"/><path d="M15 93V73H66 M241 78H280V102 M22 163H83 M239 178H283V151" stroke="#76dce7"/><path d="M150 26V14 M145 20H155 M20 146H5 M282 123H297" stroke="#74431e"/></g></svg>`;
$('#truck').innerHTML=truck;$('#system-truck').innerHTML=truck;
let ctx,ambient=[],gain,playing=false,track=0,position=0,localURL=null,toastTimer;
const tracks=[['DEEP SPACE SIGNAL',110],['AFTER THE ORBIT',146.83],['DISTANT HORIZONS',130.81]];
let prefs={motion:true,glow:true,sounds:false,intensity:100,volume:25};try{prefs={...prefs,...JSON.parse(localStorage.getItem('frontier-prefs')||'{}')}}catch{}
for(const key of ['motion','glow','sounds'])$('#'+key).checked=!!prefs[key];$('#intensity').value=prefs.intensity;$('#volume').value=prefs.volume;
function applyPrefs(){document.body.classList.toggle('no-glow',!prefs.glow);document.documentElement.style.setProperty('--intensity',prefs.intensity/100);try{localStorage.setItem('frontier-prefs',JSON.stringify(prefs))}catch{}}
applyPrefs();
function audioContext(){if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function clickSound(){if(!prefs.sounds)return;const c=audioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=650;g.gain.setValueAtTime(.018,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.065);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.07)}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function showView(view){if(!['cockpit','navigation','media','systems'].includes(view))view='cockpit';$$('.view').forEach(e=>e.classList.toggle('active',e.id===view));$$('nav button').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});history.replaceState(null,'','#'+view);window.scrollTo(0,0)}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{clickSound();showView(b.dataset.view)}));showView(location.hash.slice(1));window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));
function updatePlay(){ $$('.play').forEach(b=>{b.textContent=playing?'Ⅱ':'▶';b.setAttribute('aria-label',playing?'Pause audio':'Play audio');b.setAttribute('aria-pressed',String(playing))})}
function stopAmbient(){ambient.forEach(o=>{try{o.stop();o.disconnect()}catch{}});ambient=[];if(gain)gain.disconnect()}
function startAmbient(){stopAmbient();const c=audioContext();gain=c.createGain();gain.gain.value=prefs.volume/100*.07;gain.connect(c.destination);[1,1.5,2.003].forEach(m=>{const o=c.createOscillator();o.type='sine';o.frequency.value=tracks[track][1]*m;o.connect(gain);o.start();ambient.push(o)})}
async function togglePlay(){if(playing){$('#audio').pause();stopAmbient();playing=false}else{try{if(localURL){await $('#audio').play()}else{startAmbient()}playing=true}catch{toast('Audio could not play. Try another audio file.');playing=false}}updatePlay()}
function chooseTrack(index){const resume=playing;$('#audio').pause();$('#audio').removeAttribute('src');if(localURL)URL.revokeObjectURL(localURL);localURL=null;$('#audio-file').value='';track=(index+tracks.length)%tracks.length;position=0;$$('.track-name').forEach(e=>e.textContent=tracks[track][0]);$('#artist').textContent='FRONTIER / GENERATED AMBIENT';$('#seek').max=180;$('#duration').textContent='3:00';stopAmbient();if(resume)startAmbient();$$('.playlist button').forEach((b,i)=>b.classList.toggle('active',i===track));updateProgress()}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{clickSound();if(b.dataset.action==='play')togglePlay();else chooseTrack(track+(b.dataset.action==='next'?1:-1))}));
$('#playlist').innerHTML=tracks.map((t,i)=>`<button class="${i===0?'active':''}" data-track="${i}">0${i+1} / ${t[0]}</button>`).join('');$$('[data-track]').forEach(b=>b.onclick=()=>chooseTrack(Number(b.dataset.track)));
$('#waveform').innerHTML=Array.from({length:55},(_,i)=>`<i style="height:${15+Math.abs(Math.sin(i*1.7)*Math.cos(i*.31))*85}%"></i>`).join('');
function formatTime(n){if(!Number.isFinite(n))return '0:00';return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`}
function updateProgress(){const p=localURL?$('#audio').currentTime:position;$('#seek').value=p;$('#elapsed').textContent=formatTime(p)}
$('#seek').oninput=e=>{if(localURL&&Number.isFinite($('#audio').duration))$('#audio').currentTime=Number(e.target.value);else position=Number(e.target.value);updateProgress()};
$('#volume').oninput=e=>{prefs.volume=Number(e.target.value);$('#audio').volume=prefs.volume/100;if(gain)gain.gain.value=prefs.volume/100*.07;applyPrefs()};$('#audio').volume=prefs.volume/100;
$('#audio-file').onchange=e=>{const f=e.target.files[0];if(!f)return;stopAmbient();$('#audio').pause();if(localURL)URL.revokeObjectURL(localURL);localURL=URL.createObjectURL(f);$('#audio').src=localURL;playing=false;position=0;$$('.track-name').forEach(el=>el.textContent=f.name.replace(/\.[^.]+$/,''));$('#artist').textContent='LOCAL FILE / ON THIS DEVICE';$$('.playlist button').forEach(b=>b.classList.remove('active'));updatePlay();updateProgress();toast('Audio loaded. Press play.')};
$('#audio').addEventListener('loadedmetadata',()=>{if(Number.isFinite($('#audio').duration)){$('#seek').max=$('#audio').duration;$('#duration').textContent=formatTime($('#audio').duration)}});$('#audio').addEventListener('timeupdate',updateProgress);$('#audio').addEventListener('ended',()=>{playing=false;updatePlay()});$('#audio').addEventListener('error',()=>{if(localURL){playing=false;updatePlay();toast('This audio format could not be opened.')}});
for(const key of ['motion','glow','sounds','intensity'])$('#'+key).addEventListener('input',e=>{prefs[key]=key==='intensity'?Number(e.target.value):e.target.checked;applyPrefs()});
let routeRunning=false,routeProgress=0,zoom=1;const distances=[4.2,7.8,2.6],destinations=['DOWNTOWN','ORBITAL STATION','HOME BASE'];
function resetRoute(){routeProgress=0;routeRunning=false;$('#route-toggle').textContent='START ROUTE';$('#route-state').textContent='ROUTE READY';renderRoute()}
function renderRoute(){const selected=Number($('#destination').value),d=distances[selected];$('#remaining').textContent=(d*(1-routeProgress)).toFixed(1);$('#eta').textContent=Math.ceil(d*2.85*(1-routeProgress));$('#home-dest').textContent=destinations[selected];$('#home-distance').textContent=d.toFixed(1);const line=$('#route-line'),p=line.getPointAtLength(line.getTotalLength()*routeProgress);$('#position').setAttribute('transform',`translate(${p.x} ${p.y})`);$('#turn-distance').textContent=routeProgress>=1?'ARRIVED':(Math.max(.1,.4*(1-(routeProgress*3)%1))).toFixed(1)+' MI';$('#turn-street').textContent=routeProgress>=1?'DESTINATION REACHED':routeProgress<.3?'EAST ON KENNEDY ST':routeProgress<.7?'NORTH TOWARD MAIN ST':'EAST ON MAIN ST';$('#turn-arrow').textContent=routeProgress>=1?'◈':routeProgress<.3?'↱':routeProgress<.7?'↰':'↱'}
$('#destination').onchange=resetRoute;
$('#route-toggle').onclick=()=>{clickSound();if(routeProgress>=1)routeProgress=0;routeRunning=!routeRunning;$('#route-toggle').textContent=routeRunning?'PAUSE ROUTE':'RESUME ROUTE';$('#route-state').textContent=routeRunning?'ROUTE ENGAGED / SIMULATION':'ROUTE PAUSED';if(routeRunning)toast('Route simulation engaged');renderRoute()};
function renderZoom(){$('#map-world').setAttribute('transform',`translate(${300-300*zoom} ${250-250*zoom}) scale(${zoom})`)}$('#zoom-in').onclick=()=>{zoom=Math.min(2.5,zoom+.25);renderZoom()};$('#zoom-out').onclick=()=>{zoom=Math.max(.75,zoom-.25);renderZoom()};$('#recenter').onclick=()=>{zoom=1;renderZoom()};
let ticks=0;function tick(){if(document.hidden)return;ticks++;$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});if(prefs.motion){$('#speed').textContent=Math.round(42+Math.sin(ticks/7)*3);$('#rpm').textContent=Math.round(1840+Math.sin(ticks/7)*90).toLocaleString()}else{$('#speed').textContent='0';$('#rpm').textContent='720'}if(playing&&!localURL){position++;if(position>=180)chooseTrack(track+1);updateProgress()}if(routeRunning){routeProgress=Math.min(1,routeProgress+1/90);renderRoute();if(routeProgress>=1){routeRunning=false;$('#route-toggle').textContent='REPLAY ROUTE';$('#route-state').textContent='DESTINATION REACHED';toast('Destination reached')}}}
renderRoute();tick();setInterval(tick,1000);document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!localURL){stopAmbient();playing=false;updatePlay()}});
