'use strict';
const SoundSlots={
 'ui-tap':'Button / tab tap','ui-zoom':'Scanner / map zoom','ui-port':'Port control','ui-engage':'Route engage tone','ui-lock':'Radio lock / confirmation',
 'radar-arrival':'Target arrival','radar-departure':'Target departure','sensor-info':'Input lost / informational','sensor-warning':'Input lost / warning','sensor-critical':'Input lost / critical',
 'boot-hum':'Startup hum (loop)','boot-module':'Startup module check','boot-ready':'Startup complete','idle-hum':'Idle electrical bed (loop)','radio-scan':'Radio scanning (loop)','commission-rumble':'Commissioning power rumble','commission-vent':'Commissioning pressure vent','commission-pass':'Commissioning complete',
 'voice-start':'Starting route.','voice-resume':'Resuming route.','voice-pause':'Route paused.','voice-arrive':'Destination reached. Route complete.','voice-online':'Voice interface online.'
};
if(typeof module!=='undefined')module.exports={SoundSlots};
if(typeof window!=='undefined')(()=>{
 const buffers=new Map(),names=new Map(),active=new Map();let db=null;
 const section=document.createElement('details');section.className='panel sound-bank';section.innerHTML='<summary>CUSTOM SOUND FILES</summary><div class="sound-bank-controls"><select id="sound-slot" aria-label="Sound event"></select><input id="sound-file" type="file" accept="audio/*" aria-label="Custom sound file"><button id="sound-preview">PREVIEW</button><button id="sound-remove">RESTORE DEFAULT</button></div><p id="sound-bank-status" role="status"></p><p class="tiny">WAV or MP3 recommended. Up to 8 MB per file, 30 seconds per loop or 15 seconds per cue. Files stay on this device. Preview uses the dashboard volume.</p>';
 document.querySelector('#systems').append(section);const q=s=>document.querySelector(s);
 for(const [id,label] of Object.entries(SoundSlots)){const option=document.createElement('option');option.value=id;option.textContent=label;q('#sound-slot').append(option);}
 function status(message){q('#sound-bank-status').textContent=message||((names.get(q('#sound-slot').value)||'SYNTHESIZED DEFAULT')+(db?' / LOCAL STORAGE READY':' / SESSION ONLY'));}
 function stop(id){const n=active.get(id);if(n){try{n.source.stop();}catch{}n.source.disconnect();n.gain.disconnect();active.delete(id);}}
 function play(id,{loop=false,volume=1}={}){const buffer=buffers.get(id);if(!buffer||document.hidden)return false;try{const c=audioContext();if(c.state!=='running')return false;if(loop&&active.has(id)){active.get(id).gain.gain.value=Math.max(0,Math.min(1,prefs.volume/100*volume));return true;}stop(id);const source=c.createBufferSource(),gain=c.createGain();source.buffer=buffer;source.loop=loop;gain.gain.value=Math.max(0,Math.min(1,prefs.volume/100*volume));source.connect(gain).connect(c.destination);active.set(id,{source,gain,volume});source.onended=()=>{if(active.get(id)?.source===source)active.delete(id);source.disconnect();gain.disconnect();};source.start();return true;}catch{return false;}}
 function write(id,file){return new Promise((resolve,reject)=>{if(!db)return reject(Error('Session only'));const tx=db.transaction('sounds','readwrite');if(file)tx.objectStore('sounds').put({id,name:file.name,file});else tx.objectStore('sounds').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 async function decode(file,id){if(file.size>8*1024*1024)throw Error('File exceeds 8 MB');const buffer=await audioContext().decodeAudioData(await file.arrayBuffer());if(buffer.duration>(/hum|scan/.test(id)?30:15))throw Error('Audio is too long for this slot');return buffer;}
 q('#sound-file').onchange=async e=>{const file=e.target.files[0],id=q('#sound-slot').value;if(!file)return;try{await audioContext().resume();const buffer=await decode(file,id);stop(id);buffers.set(id,buffer);names.set(id,file.name);try{await write(id,file);status('SAVED / '+file.name);}catch{status('LOADED FOR THIS SESSION / '+file.name);}window.SurfaceAudio?.stopIdleBed();window.SurfaceAudio?.syncIdleBed();}catch(error){status('NOT LOADED / '+error.message);}finally{e.target.value='';}};
 q('#sound-slot').onchange=()=>status();q('#sound-preview').onclick=async()=>{try{await audioContext().resume();const id=q('#sound-slot').value;if(!play(id))status('No custom file assigned to this event.');}catch{status('Audio unavailable.');}};
 q('#sound-remove').onclick=async()=>{const id=q('#sound-slot').value;try{if(db)await write(id,null);stop(id);buffers.delete(id);names.delete(id);status();window.SurfaceAudio?.stopIdleBed();window.SurfaceAudio?.syncIdleBed();}catch{status('Could not remove saved file. Try again.');}};
 window.CustomSounds={play,stop,has:id=>buffers.has(id),setVolume(){for(const n of active.values())n.gain.gain.value=Math.max(0,Math.min(1,prefs.volume/100*n.volume));}};
 document.addEventListener('visibilitychange',()=>{if(document.hidden)for(const id of [...active.keys()])stop(id);});
 try{const request=indexedDB.open('surface-custom-sounds',1);request.onupgradeneeded=()=>request.result.createObjectStore('sounds',{keyPath:'id'});request.onsuccess=()=>{db=request.result;const read=db.transaction('sounds').objectStore('sounds').getAll();read.onsuccess=async()=>{for(const row of read.result){if(!SoundSlots[row.id])continue;try{buffers.set(row.id,await decode(row.file,row.id));names.set(row.id,row.name);}catch{}}status();};status();};request.onerror=()=>status('Local storage unavailable / files last for this session only.');}catch{status();}status();
})();
