'use strict';
(() => {
  const q=s=>document.querySelector(s), shell=q('.shell');
  const overlay=document.createElement('div');overlay.id='ship-startup';overlay.tabIndex=-1;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Thirty second ship startup');
  overlay.innerHTML=`<div class="ignition-console"><div class="ignition-top"><span>SURFACE COMMAND / COLD START</span><strong id="boot-countdown">30.0 S</strong></div><div class="ignition-reactor" aria-hidden="true"><svg viewBox="0 0 240 180"><g class="reactor-outer"><circle cx="120" cy="90" r="76"/><path d="M120 8V23 M120 157V172 M38 90H53 M187 90H202"/></g><g class="reactor-inner"><circle cx="120" cy="90" r="56"/><path d="M120 30L172 120H68Z"/></g><circle class="reactor-heart" cx="120" cy="90" r="25"/><path d="M0 90H35 M205 90H240"/></svg><div><small>IGNITION SEQUENCE</small><h1 id="boot-phase">CORE ENERGIZING</h1><p id="boot-sound-status">AUDIO / STARTING</p></div></div><div class="boot-energy" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div id="boot-modules"></div><progress id="boot-progress" max="30" value="0" aria-label="Thirty second startup progress"></progress><p id="boot-status" role="status">Initializing interface</p><small class="boot-disclaimer">Interface sequence · no engine warm-up measurement</small></div>`;
  document.body.append(overlay);
  const stages=[['POWER DISTRIBUTION','INTERFACE READY'],['DISPLAY PROJECTORS','ONLINE'],['CONTROL BUS','ONLINE'],['NAVIGATION','DEMO MAP LOADED'],['AUDIO PROCESSOR','READY'],['BACKUP RADIO','FILE PLAYER READY'],['ANTENNA TUNER','HARDWARE UNAVAILABLE'],['ESP32 SENSOR LINK',()=>q('#port-state')?.textContent==='DEVICE ONLINE'?'DEVICE ONLINE':'HARDWARE UNAVAILABLE'],['CAMERA ARRAY','HARDWARE UNAVAILABLE'],['ULTRASONIC ARRAY','HARDWARE UNAVAILABLE'],['ENGINE / OBD','HARDWARE UNAVAILABLE'],['COMMAND INTERFACE','READY']];
  let startTime=0,timer=null,lastStage=-1,closed=true,hum=null,humGain=null;
  function stopHum(){if(hum){try{hum.stop();hum.disconnect();humGain.disconnect()}catch{}hum=null;humGain=null}}
  function startHum(c){if(closed||document.hidden||c.state!=='running'||hum)return;hum=c.createOscillator();humGain=c.createGain();hum.type='sine';hum.frequency.setValueAtTime(42,c.currentTime);hum.frequency.linearRampToValueAtTime(78,c.currentTime+Math.max(0,30-(performance.now()-startTime)/1000));humGain.gain.setValueAtTime(.035*prefs.volume/100,c.currentTime);hum.connect(humGain).connect(c.destination);hum.start();}
  function unlock(){if(closed)return;try{const c=audioContext();q('#boot-sound-status').textContent=c.state==='running'?'AUDIO / ONLINE':'TAP ANYWHERE FOR STARTUP AUDIO';startHum(c);c.resume().then(()=>{if(!closed){q('#boot-sound-status').textContent=c.state==='running'?'AUDIO / ONLINE':'AUDIO / UNAVAILABLE';startHum(c)}}).catch(()=>{if(!closed)q('#boot-sound-status').textContent='AUDIO / UNAVAILABLE'});}catch{q('#boot-sound-status').textContent='AUDIO / UNAVAILABLE'}}
  function cue(stage){try{const c=audioContext();if(c.state!=='running'||document.hidden)return;[0,.09].forEach((delay,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=i?'sine':'triangle';o.frequency.setValueAtTime((stage>=6&&stage<=10?85:125)+stage*8,t);o.frequency.exponentialRampToValueAtTime(i?55:90,t+.3);g.gain.setValueAtTime(.09*prefs.volume/100,t);g.gain.exponentialRampToValueAtTime(.0001,t+.4);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.42);o.onended=()=>{o.disconnect();g.disconnect()};});}catch{}}
  function finish(){closed=true;clearTimeout(timer);stopHum();overlay.hidden=true;shell.inert=false;document.body.classList.remove('booting');document.dispatchEvent(new Event('surface-startup-complete'));q('nav button[aria-current]')?.focus({preventScroll:true});}
  function tick(){if(closed)return;const elapsed=Math.max(0,performance.now()-startTime);if(elapsed>=30000){finish();return}const stage=Math.min(11,Math.floor(elapsed/2500));q('#boot-countdown').textContent=((30000-elapsed)/1000).toFixed(1)+' S';q('#boot-progress').value=elapsed/1000;if(stage!==lastStage){lastStage=stage;q('#boot-phase').textContent=stages[stage][0];q('#boot-status').textContent='SEQUENCE '+String(stage+1).padStart(2,'0')+' / 12';q('#boot-modules').replaceChildren();stages.forEach(([name,state],i)=>{const row=document.createElement('div');row.className='boot-module '+(i===stage?'module-current':i<stage?'module-complete':'module-pending');const label=document.createElement('span'),value=document.createElement('b');label.textContent=name;value.textContent=i>stage?'STANDBY':typeof state==='function'?state():state;if(value.textContent==='HARDWARE UNAVAILABLE')row.classList.add('module-unavailable');row.append(label,value);q('#boot-modules').append(row)});cue(stage)}timer=setTimeout(tick,100);}
  function start(){clearTimeout(timer);stopHum();closed=false;lastStage=-1;startTime=performance.now();overlay.hidden=false;shell.inert=true;document.body.classList.add('booting');overlay.focus({preventScroll:true});unlock();tick();}
  overlay.addEventListener('pointerdown',unlock);overlay.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();overlay.focus({preventScroll:true})}unlock()});
  document.addEventListener('visibilitychange',()=>{if(closed)return;if(document.hidden)stopHum();else{clearTimeout(timer);tick();if(!closed)unlock()}});
  const replay=document.createElement('button');replay.textContent='REPLAY 30-SECOND STARTUP';replay.onclick=start;q('#systems .systems-layout').after(replay);start();
})();
