'use strict';
(()=>{
 const q=s=>document.querySelector(s),section=document.createElement('section');section.id='parking';section.className='view';section.setAttribute('aria-label','Parking');
 section.innerHTML='<div class="section-heading"><h1>PARKING</h1><button id="leave-parking">EXIT PARKING</button></div><div class="parking-layout"><article class="panel"><div class="panel-title">CAMERA / LIVE VIEW</div><video id="parking-video" autoplay muted playsinline></video><div class="parking-controls"><select id="parking-camera" aria-label="Parking camera"><option value="">Default rear-facing camera</option></select><button id="parking-start">ENABLE CAMERA</button><button id="parking-stop">CAMERA OFF</button></div><p id="parking-camera-status" role="status">CAMERA OFF / Permission required. No recording.</p></article><article class="panel"><div class="panel-title">CLOSE RANGE / 5 M</div><svg id="parking-scope" viewBox="0 0 360 220" aria-label="Nearby reported contacts"></svg><div id="parking-readings" class="parking-status"></div><p class="tiny">An empty view is not an all-clear. Sensor readings are unverified and must not replace checking your surroundings. No inferred steering guidelines.</p></article></div>';
 q('main').append(section);
 for(const selector of ['#cockpit .cockpit-driving-info','#navigation .subtabs','#proximity .section-heading']){const target=q(selector);if(!target)continue;const button=document.createElement('button');button.textContent='PARKING';button.onclick=()=>showView('parking');target.append(button);}
 let stream=null,version=0,enabled=false;
 function stop(message='CAMERA OFF'){version++;enabled=false;stream?.getTracks().forEach(t=>t.stop());stream=null;q('#parking-video').srcObject=null;q('#parking-camera-status').textContent=message;}
 async function list(){const devices=await navigator.mediaDevices.enumerateDevices(),selected=q('#parking-camera').value;const select=q('#parking-camera');select.replaceChildren();const first=document.createElement('option');first.value='';first.textContent='Default rear-facing camera';select.append(first);devices.filter(d=>d.kind==='videoinput').forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Camera '+(i+1);select.append(o);});select.value=selected;}
 async function start(){stop();if(!navigator.mediaDevices?.getUserMedia){q('#parking-camera-status').textContent='CAMERA API UNAVAILABLE / Native head-unit camera bridge required';return;}const ticket=version;enabled=true;const id=q('#parking-camera').value;q('#parking-camera-status').textContent='OPENING CAMERA…';try{const next=await navigator.mediaDevices.getUserMedia({video:id?{deviceId:{exact:id}}:{facingMode:{ideal:'environment'}},audio:false});if(ticket!==version||document.hidden){next.getTracks().forEach(t=>t.stop());return;}stream=next;q('#parking-video').srcObject=stream;await q('#parking-video').play();if(ticket!==version)return;q('#parking-camera-status').textContent='LIVE / '+(stream.getVideoTracks()[0]?.label||'CAMERA');stream.getVideoTracks()[0]?.addEventListener('ended',()=>{if(ticket===version)stop('CAMERA DISCONNECTED');});await list();}catch(e){if(ticket===version)stop('CAMERA UNAVAILABLE / '+e.name);}}
 q('#parking-start').onclick=start;q('#parking-stop').onclick=()=>stop();q('#parking-camera').onchange=()=>{if(enabled)start();};q('#leave-parking').onclick=()=>showView('cockpit');
 window.addEventListener('surface-view',e=>{if(e.detail.view!=='parking')stop();else render();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
 navigator.mediaDevices?.addEventListener?.('devicechange',()=>{if(enabled)list().catch(()=>{});});
 function render(){if(!section.classList.contains('active'))return;SurfacePerception.renderParking(q('#parking-scope'));const contacts=SurfacePerception.contacts().filter(c=>c.distanceMeters<=5);const readings=q('#parking-readings');readings.replaceChildren();for(const [label,min,max]of [['FRONT',-45,45],['RIGHT',45,135],['REAR',135,225],['LEFT',225,315]]){const values=contacts.filter(c=>{let b=((c.bearingDegrees%360)+360)%360;if(label==='FRONT'&&b>315)b-=360;return b>=min&&b<max;});const nearest=values.length?Math.min(...values.map(c=>c.distanceMeters)):null;const row=document.createElement('p');row.textContent=label+' / '+(nearest===null?'NO FRESH MEASUREMENT':nearest.toFixed(2)+' M · REPORTED');readings.append(row);}const speed=window.SurfaceTelemetry?.current().speed;const row=document.createElement('p');row.textContent='SPEED / '+(Number.isFinite(speed)?speed.toFixed(1)+' MPH':'UNAVAILABLE');readings.append(row);}
 setInterval(render,250);if(location.hash==='#parking')showView('parking');
})();
