'use strict';
(() => {
  const overlay=document.createElement('div');overlay.id='ship-startup';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Ship interface startup');
  overlay.innerHTML='<div class="boot-core"><small>SURFACE COMMAND / INITIALIZATION</small><h1>CORE IGNITION</h1><div class="boot-reactor" aria-hidden="true">◎</div><div id="boot-modules" aria-live="polite"></div><progress id="boot-progress" max="6" value="0" aria-label="Startup progress"></progress><p id="boot-status">Starting interface modules…</p><p class="tiny">Interface startup only. Engine temperature and vehicle self-checks are unavailable.</p><div class="boot-actions"><button id="boot-sound">ENABLE STARTUP SOUND</button><button id="boot-skip">ENTER COCKPIT / SKIP</button></div></div>';
  document.body.append(overlay);
  const shell=document.querySelector('.shell');let step=0,timer,closed=false,audible=false,priorFocus;
  const stages=[['DISPLAY BUS','READY'],['NAVIGATION CORE','DEMO MAP LOADED'],['AUDIO BUS','READY / TAP TO PLAY'],['ESP32 LINK','CHECK PORT TAB'],['PERCEPTION ARRAY','NO LIVE DETECTOR'],['ENGINE / OBD','NOT CONNECTED']];
  function tone(index){if(!audible||document.hidden)return;try{const c=audioContext();if(c.state!=='running')return;const o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.setValueAtTime(55+index*18,c.currentTime);o.frequency.exponentialRampToValueAtTime(40,c.currentTime+.3);g.gain.setValueAtTime(.035*prefs.volume/100,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.4);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.42);o.onended=()=>{o.disconnect();g.disconnect()};}catch{}}
  function finish(){closed=true;clearTimeout(timer);overlay.hidden=true;shell.inert=false;document.body.classList.remove('booting');(priorFocus?.isConnected?priorFocus:document.querySelector('nav button[aria-current]'))?.focus();}
  function advance(){if(closed)return;const row=document.createElement('div');row.className='boot-module';const label=document.createElement('span'),value=document.createElement('b');label.textContent=stages[step][0];value.textContent=stages[step][1];row.append(label,value);document.querySelector('#boot-modules').append(row);tone(step);step++;document.querySelector('#boot-progress').value=step;document.querySelector('#boot-status').textContent=step===6?'INTERFACE READY':'INITIALIZING / '+stages[step][0];timer=setTimeout(step===6?finish:advance,step===6?1100:1450);}
  function start(){clearTimeout(timer);priorFocus=document.activeElement;step=0;closed=false;overlay.hidden=false;shell.inert=true;document.body.classList.add('booting');document.querySelector('#boot-modules').replaceChildren();document.querySelector('#boot-progress').value=0;document.querySelector('#boot-status').textContent='Starting interface modules…';document.querySelector('#boot-skip').focus();timer=setTimeout(advance,450);}
  document.querySelector('#boot-skip').onclick=finish;
  document.querySelector('#boot-sound').onclick=async()=>{try{await audioContext().resume();if(closed)return;audible=!audible;document.querySelector('#boot-sound').textContent=audible?'MUTE STARTUP SOUND':'ENABLE STARTUP SOUND';tone(step);}catch{document.querySelector('#boot-status').textContent='Sound unavailable; visual startup continues.'}};
  overlay.addEventListener('keydown',e=>{if(e.key==='Escape')finish();if(e.key==='Tab'){const first=document.querySelector('#boot-sound'),last=document.querySelector('#boot-skip');if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
  const replay=document.createElement('button');replay.textContent='REPLAY SHIP STARTUP';replay.onclick=start;document.querySelector('#systems .systems-layout').after(replay);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&!closed)finish()});start();
  // Existing file decoding, playback state and errors stay owned by app.js.
  const input=document.querySelector('#audio-file'),original=input.onchange;input.multiple=true;
  input.parentElement.firstChild.textContent='BACKUP RADIO / LOAD AUDIO FILES';
  const list=document.createElement('div');list.className='backup-library';list.setAttribute('aria-label','Backup Radio files');input.parentElement.after(list);
  input.onchange=e=>{const files=Array.from(e.target.files);if(!files.length)return;list.replaceChildren();for(const file of files){const b=document.createElement('button');b.textContent=file.name;b.onclick=()=>original({target:{files:[file]}});list.append(b)}original({target:{files:[files[0]]}});};
  const info=document.createElement('article');info.className='panel antenna-info';info.innerHTML='<div class="panel-title">ANTENNA RADIO <span>HARDWARE ACCESS UNAVAILABLE</span></div><p>This browser cannot tune an iPhone or truck antenna. Truck reception requires its native radio app or a verified head-unit tuner integration.</p><a href="https://music.apple.com/radio" target="_blank" rel="noopener">OPEN INTERNET RADIO IN APPLE MUSIC ↗</a><p class="tiny">Internet connection required. The frequency dial below remains a synthetic demo. Backup Radio plays your selected local files without uploading them; choose the files again after a reload.</p>';
  document.querySelector('#radio .section-heading').after(info);
})();
