'use strict';
(()=>{
 const q=s=>document.querySelector(s),button=document.createElement('button');button.id='system-stress-test';button.textContent='RUN DISPLAY & SOUND TEST / PARKED';q('#systems .systems-layout').after(button);
 const overlay=document.createElement('section');overlay.id='commissioning';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-label','Parked display and sound test');overlay.innerHTML=`<div class="commission-frame"><div class="commission-top"><span>DISPLAY TEST / SIMULATED</span><b id="commission-clock">T—00:00</b><button id="stop-system-test">ABORT</button></div><div class="commission-stage"><div class="steam left">${'<i></i>'.repeat(6)}</div><div class="steam right">${'<i></i>'.repeat(6)}</div><div class="reactor"><div class="reactor-rings"><i></i><i></i><i></i><b>CORE<br><span id="commission-percent">0%</span></b></div><div class="energy-rail"><i></i></div></div><div class="commission-copy"><small id="commission-kicker">PARKED DISPLAY TEST</small><h1 id="commission-title">AWAITING AUTHORIZATION</h1><p id="test-step">Vehicle must remain parked.</p></div></div><div id="commission-modules" class="commission-modules"></div><div class="commission-progress"><i id="commission-fill"></i></div><div class="commission-footer"><span>SIMULATED LOADS / LIVE INPUTS PROTECTED</span><strong id="commission-result">HOLD</strong></div></div>`;document.body.append(overlay);
 const names=['POWER BUS','DISPLAY CORE','PERCEPTION','NAVIGATION','ESP32 LINK','CAMERA ARRAY','AUDIO ROUTER','TELEMETRY'];const modules=names.map(name=>{const row=document.createElement('div');row.innerHTML=`<span>${name}</span><i></i><b>STANDBY</b>`;q('#commission-modules').append(row);return row;});
 let runVersion=0,timer=null,animation=null,index=0,elapsed=0,previousView='',previousPins=false,savedLimit=null,audioNodes=[];
 const targets=[{type:'CAR',headingDegrees:30,confidence:.96},{type:'CAR',confidence:.78},{type:'PERSON',confidence:.9},{type:'ANIMAL',confidence:.7},{type:'MISC',confidence:.52}].map((c,i)=>({...c,id:'commission-'+i,distanceMeters:28+i*26,bearingDegrees:-72+i*36}));
 function stopAudio(){audioNodes.forEach(n=>{try{n.stop?.();n.disconnect?.();}catch{}});audioNodes=[];for(const id of ['commission-rumble','commission-vent','commission-pass'])window.CustomSounds?.stop(id);}
 function sound(kind){if(window.CustomSounds?.play('commission-'+kind,{volume:kind==='rumble'?.45:.8,loop:kind==='rumble'}))return;try{const c=audioContext();if(c.state!=='running')return;if(kind==='vent'){const buffer=c.createBuffer(1,c.sampleRate*.7,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=buffer;filter.type='bandpass';filter.frequency.value=1050;gain.gain.value=.11*prefs.volume/100;src.connect(filter).connect(gain).connect(c.destination);src.start();audioNodes.push(src,filter,gain);return;}const notes=kind==='pass'?[330,440,660]:[48,72],duration=kind==='rumble'?4:.32;notes.forEach((hz,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.08;o.type=i?'triangle':'sawtooth';o.frequency.setValueAtTime(hz,t);if(kind==='rumble')o.frequency.linearRampToValueAtTime(hz*1.25,t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,(kind==='rumble'?.035:.1)*prefs.volume/100),t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(c.destination);o.start(t);o.stop(t+duration);audioNodes.push(o,g);});}catch{}}
 function animate(duration,frame){let spent=0,version=runVersion;const tick=()=>{if(version!==runVersion)return;frame(Math.min(1,spent/duration));spent+=50;if(spent<=duration)animation=setTimeout(tick,50);};tick();}
 function setModule(i,state){if(!modules[i])return;modules[i].dataset.state=state.toLowerCase();modules[i].querySelector('b').textContent=state;}
 function moduleStatus(i){if(i===4)return /ONLINE/.test(q('#port-state')?.textContent||'')?'PASS':'STANDBY';if(i===5)return 'STANDBY';return 'PASS';}
 function sweep(view,duration=1300){showView(view);animate(duration,p=>{const wave=Math.sin(p*Math.PI);window.SurfaceDisplayTest.frame({speed:150*wave,rpm:7500*wave,coolant:160+55*wave,voltage:12+2.5*wave,load:wave*100,throttle:wave*100});q('#speed-limit').textContent=String([15,25,35,45,55,65,70][Math.min(6,Math.floor(p*7))]);q('.speed-limit-card small').textContent='DISPLAY TEST LOAD';});}
 const phases=[
  {title:'DISPLAY INITIALIZATION',copy:'Preparing isolated display-test readings',duration:1300,module:0,run(){overlay.dataset.phase='charge';}},
  {title:'CONTROL RESPONSE',copy:'Checking test controls and display transitions',duration:1000,module:1,run(){overlay.dataset.phase='vent';}},
  {title:'SCANNER MODE CHECK',copy:'Map, road and traffic layers resolving',duration:1500,module:2,run(){overlay.dataset.phase='scan';showView('proximity');let modes=['map','road','vehicle','proximity'],i=0,version=runVersion;const cycle=()=>{if(version!==runVersion)return;if(i<modes.length){SurfacePerception.test(targets,modes[i++]);animation=setTimeout(cycle,310);}};cycle();}},
  {title:'PERCEPTION SATURATION',copy:'25 moving tracks // classification and confidence load',duration:1500,module:2,run(){showView('proximity');animate(1400,p=>SurfacePerception.test(Array.from({length:25},(_,i)=>({...targets[i%5],id:'load-'+i,distanceMeters:12+(i*11+p*65)%180,bearingDegrees:i*137+p*55})),'proximity'));window.radarTone?.('arrival',true);}},
  {title:'SPEED & RPM SWEEP',copy:'Speed and engine instruments sweeping operating display range',duration:1500,module:7,run(){overlay.dataset.phase='load';sweep('data');}},
  {title:'NAVIGATION DISPLAY',copy:'Route renderer and speed-limit channel under simulated load',duration:1450,module:3,run(){overlay.dataset.phase='nav';sweep('navigation');}},
  {title:'ESP32 PIN DISPLAY',copy:'ESP32 pin matrix and hardware interfaces',duration:900,module:4,run(){showView('port');q('#pin-preview').checked=true;q('#pin-preview').dispatchEvent(new Event('change'));}},
  {title:'CAMERA STATUS',copy:'Camera interfaces waiting for physical hardware authorization',duration:750,module:5,run(){showView('parking');}},
  {title:'AUDIO ROUTER BURST',copy:'Transient alerts // warning escalation // output path',duration:850,module:6,run(){showView('systems');window.SurfaceAlerts?.testTone?.('warning');}},
  {title:'RESTORING LIVE DISPLAY',copy:'Comparing module responses and restoring live channels',duration:900,module:7,sound:'pass',run(){overlay.dataset.phase='complete';}}
 ];
 function restore(){runVersion++;if(timer)clearTimeout(timer);if(animation)clearTimeout(animation);timer=animation=null;stopAudio();window.SurfaceDisplayTest.stop();SurfacePerception.test(null);if(savedLimit){q('#speed-limit').textContent=savedLimit.value;q('.speed-limit-card small').textContent=savedLimit.label;}q('#pin-preview').checked=previousPins;q('#pin-preview').dispatchEvent(new Event('change'));button.disabled=false;showView(previousView);}
 function finish(){q('#commission-title').textContent='DISPLAY TEST COMPLETE';q('#test-step').textContent='Display exercise finished. Hardware not validated.';q('#commission-result').textContent='READY';q('#commission-percent').textContent='100%';q('#commission-fill').style.width='100%';overlay.dataset.phase='complete';sound('pass');timer=setTimeout(()=>{restore();overlay.hidden=true;},1500);}
 function next(){if(index>=phases.length){finish();return;}const phase=phases[index],version=runVersion;elapsed+=phase.duration;q('#commission-clock').textContent='T+'+(elapsed/1000).toFixed(1)+'S';q('#commission-title').textContent=phase.title;q('#test-step').textContent=phase.copy;q('#commission-kicker').textContent=`SEQUENCE ${String(index+1).padStart(2,'0')} / ${phases.length}`;q('#commission-percent').textContent=Math.round(index/phases.length*100)+'%';q('#commission-fill').style.width=index/phases.length*100+'%';setModule(phase.module,'TESTING');phase.sound&&sound(phase.sound);phase.run();timer=setTimeout(()=>{if(version!==runVersion)return;setModule(phase.module,moduleStatus(phase.module));index++;next();},phase.duration);}
 button.onclick=async()=>{if(button.disabled)return;if((window.SurfaceTelemetry?.current().speed??0)>0){toast('Commissioning requires the vehicle to be stopped');return;}button.disabled=true;const version=++runVersion;previousView=location.hash.slice(1)||'systems';previousPins=q('#pin-preview').checked;savedLimit={value:q('#speed-limit').textContent,label:q('.speed-limit-card small').textContent};modules.forEach((_,i)=>setModule(i,'STANDBY'));index=elapsed=0;overlay.hidden=false;overlay.dataset.phase='idle';q('#commission-result').textContent='RUNNING';try{const c=audioContext();await c.resume();}catch{}if(version===runVersion)next();};
 q('#stop-system-test').onclick=()=>{restore();overlay.hidden=true;toast('Commissioning aborted');};
 window.addEventListener('surface-telemetry',e=>{if(!overlay.hidden&&Number.isFinite(e.detail.speed)&&e.detail.speed>0){restore();q('#commission-title').textContent='SEQUENCE ABORTED';q('#test-step').textContent='VEHICLE MOVING // commissioning interlock engaged';q('#commission-result').textContent='ABORT';overlay.hidden=true;toast('Commissioning aborted / vehicle moving');}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!overlay.hidden){restore();overlay.hidden=true;}});
})();
