'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {parse,remainingRoute}=require('../port-protocol.js');
assert.equal(parse('{"type":"hello","protocol":"surface-port/1","device":"ESP32","firmware":"starter-1.0"}').device,'ESP32');
assert.equal(parse('{"type":"sensors","values":[{"id":"board_uptime","value":1,"unit":"s"}]}').values[0].value,1);
assert.equal(parse('{"type":"power","usb_present":false}').usb_present,false);
assert.deepEqual(parse('{"type":"sensors","values":[]}').values,[]);
for(const bad of ['null','[]','not json','{"type":"power","usb_present":"true"}','{"type":"hello","protocol":"other","device":"ESP32","firmware":"1"}','x'.repeat(4097),'{"type":"sensors","values":[{"id":"x","value":1e300,"unit":"V"}]}','{"type":"sensors","values":[{"id":"<script>","value":1,"unit":"V"}]}']) assert.throws(()=>parse(bad));
assert.throws(()=>parse(JSON.stringify({type:'sensors',values:Array.from({length:25},(_,i)=>({id:'x'+i,value:1,unit:'V'}))})));
assert.throws(()=>parse(JSON.stringify({type:'sensors',values:[{id:'x',value:1,unit:'V'},{id:'x',value:2,unit:'V'}]})));
assert.equal(remainingRoute(0),'M172.000 440.000L172 272L388 272L388 150L480 150');
assert.equal(remainingRoute(1),'');assert.equal(remainingRoute(2),'');
assert.equal(remainingRoute(168/598),'M172.000 272.000L388 272L388 150L480 150');
assert.equal(remainingRoute(.5),'M303.000 272.000L388 272L388 150L480 150');
assert.equal(remainingRoute(-1),remainingRoute(0));
const html=fs.readFileSync(require.resolve('../index.html'),'utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
assert(html.includes('id="route-geometry"'));assert(html.includes('data-view="port"'));
console.log('PASS: packet validation, malformed/oversized packets, route start/corners/progress/arrival, unique IDs and Port navigation');
